[package]
name = "minicloud"
version = "0.3.1"
edition = "2021"
author = ["slplsswkds <slplsswkds@protonmail.com>"]

[dependencies]
clap = { version = "4.4.12", features = ["derive"] }  # --- Arguments parsing
#wild = "2.2.0"  # --- Augment clap: for supporting wildcards (*) on Windows like you do Linux
tokio = { version = "1.35.1", features = ["full"] }
axum = { version = "0.7.3" }
tokio-util = { version = "0.7.10", features = ["full"] }
serde = { version = "1.0.193", features = ["derive"] }
colored = { version = "2.0.4" }
mime_guess = { version = "2.0.4" }
local-ip-address = "0.5.6"
html = "0.6.3"