[package]
name = "minicloud"
version = "0.14.6"
edition = "2021"

# ------------------------- Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# ------------------------- Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

# ------------------------- Release Mode Optimizations
# Enable more optimization in the release profile at the cost of compile time.
[profile.release]
# Compile the entire crate as one unit.
# Slows compile times, marginal improvements.
codegen-units = 1
# Do a second optimization pass over the entire program, including dependencies.
# Slows compile times, marginal improvements.
lto = "thin"

# ------------------------- Alternative Linker
# for Linux
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# for Windows
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4", features = ["derive"] }
#wild = "2.2"  # --- Augment clap: for supporting wildcards (*) on Windows like you do on Linux
# tokio = { version = "1", features = ["full"] }
tokio = { version = "1", features = ["full"] }
axum = { version = "0.8", features = ["multipart"] }
local-ip-address = "0.6"
serde = { version = "1", features = ["derive"] }
tokio-util = { version = "0.7", features = ["io"] }
mime_guess = "2"
tower-http = { version = "0.7", features = ["limit", "trace"] }
askama = "0.16"
